name: ci-cd production

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to droplet via SSH action
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY_PROD }}
          script: |
            cd ./ateverse-frontend
            git pull origin main
            cp -r ./public ../ateverse-infra/nginx
            cd ../ateverse-infra
            docker rm --force ateverse-nginx
            docker build -t ateverse-nginx ./nginx
            docker run -d --restart always --name ateverse-nginx \
              -v ~/ateverse-infra/nginx/public:/var/www/html/app \
              -v /etc/letsencrypt:/etc/letsencrypt \
              -p 80:80 -p 443:443 --network ateverse-network ateverse-nginx
